site:
  name: Kodeloom
  site: 'https://kodeloom.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: dd

# Default SEO metadata
metadata:
  title:
    default: Kodeloom Software Solutions
    template: '%s — Kodeloom'
  description: "Boost your business online presence with Kodeloom Software Solutions. We offer custom website development, e-commerce solutions, SEO services, website hosting and more. Improve your digital presence with our team and innovative solutions. Contact us today to bring your online success!"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Kodeloom
    images:
      - url: '~/assets/images/default.jpg'
        width: 1200
        height: 630
    type: website
  twitter:
    handle: '@kodeloom'
    site: '@kodeloom'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
